CREATE TABLE IF NOT EXISTS capacity_building (
    staffid               BIGINT PRIMARY KEY,
    fullname              VARCHAR(255),
    reg_date              TIMESTAMP NULL,
    decision              VARCHAR(64),
    training_type         VARCHAR(128),
    staff_type            VARCHAR(128),
    nrc                   VARCHAR(64),
    sex                   VARCHAR(16),
    age                   INT,
    job_role              VARCHAR(128),
    education             VARCHAR(128),
    used_smartcare        VARCHAR(32),
    currently_using       VARCHAR(32),
    stakeholder_name      VARCHAR(255),
    facility_name         VARCHAR(255),
    province_name         VARCHAR(128),
    district_name         VARCHAR(128),
    financialyear         VARCHAR(8),
    quarters              VARCHAR(4),
    isocode               VARCHAR(8),
    pretestdate           TIMESTAMP NULL,
    pretestscore          INT,
    posttestdate          TIMESTAMP NULL,
    posttestscore         INT,
    mgr_pretestdate       TIMESTAMP NULL,
    mgr_pretestscore      INT,
    mgr_posttestdate      TIMESTAMP NULL,
    mgr_posttestscore     INT,
    inserted_at           TIMESTAMP DEFAULT NOW(),
    updated_at            TIMESTAMP DEFAULT NOW()
);
